@startuml test

class Parent {
    + public_member: type
    # protected_member: type
    - private_member: type

    {static} static_member: type

    + public_method(param: type): return_type
    # public_method(param: type): return_type
    - public_method(param: type): return_type

    {static} static_method(param: type): return_type
}

class Child {
    + public_member: type
    # protected_member: type
    - private_member: type

    {static} static_member: type

    + public_method(param: type): return_type
    # public_method(param: type): return_type
    - public_method(param: type): return_type

    {static} static_method(param: type): return_type
}

Parent <|-- Child

@enduml